#!/bin/bash

#set -x

#JCKIT=/home/tews/java/card/jckits/jc222
#APDUIOJAR=$JCKIT/lib/apduio.jar

WRAPPER_DIR="/home/tews/OV/src/emulator/wrapper"

java -ea -classpath $WRAPPER_DIR/_java_build_dir/wrapper \
    ds/javacard/emulator/wrapper/Wrapper $*
