//!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
//!!!   DO NOT EDIT OR CHANGE THIS FILE. CHANGE THE ORIGINAL INSTEAD.      !!!
//!!!   THIS FILE HAS BEEN GENERATED BY CPP AND SED,                       !!!
//!!!   BECAUSE JAVA DOES NOT SUPPORT CONDITIONAL COMPILATION.             !!!
//!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
//# 1 "/tmp/tews/ov-dist/ov-chip-2-2010-09-20/test/Exponent_perf_description.java"
//# 1 "<built-in>"
//# 1 "<command-line>"
//# 1 "/tmp/tews/ov-dist/ov-chip-2-2010-09-20/test/Exponent_perf_description.java"
// DO NOT EDIT! DO NOT EDIT! DO NOT EDIT! DO NOT EDIT! DO NOT EDIT! 
//
// This file has been generated automatically from Exponent_perf.id
// by some sort of idl compiler.

//# 1 "./config" 1
// 
// OV-chip 2.0 project
// 
// Digital Security (DS) group at Radboud Universiteit Nijmegen
// 
// Copyright (C) 2008, 2009
// 
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License as
// published by the Free Software Foundation; either version 2 of
// the License, or (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
// General Public License in file COPYING in this or one of the
// parent directories for more details.
// 
// Created 26.7.08 by Hendrik
// 
// preprocessor config directives
// 
// $Id: config,v 1.17 2010-02-16 10:26:10 tews Exp $
//# 53 "./config"
  // For the jcwde emulator the applet class must be public
//# 91 "./config"
/// Local Variables:
/// mode: c
/// End:
//# 7 "/tmp/tews/ov-dist/ov-chip-2-2010-09-20/test/Exponent_perf_description.java" 2


  package ov_test;






  import javacard.framework.APDU;
//# 39 "/tmp/tews/ov-dist/ov-chip-2-2010-09-20/test/Exponent_perf_description.java"
/**
 * Protocol description for Exponent_perf. Defines suitable Protocol's and Protocol_steps for all protocols described in Exponent_perf.id for use in the OV-chip protocol layer.
 * 
 * @author idl compiler
 * @version automatically generated from Exponent_perf.id
 * @environment host, card
 * @CPP This class uses the following cpp defines:
 *   <a href="../../../overview-summary.html#PACKAGE">PACKAGE</a>,
 *   <a href="../../../overview-summary.html#JAVACARD_APPLET">JAVACARD_APPLET</a>,
 *   <a href="../../../overview-summary.html#APPLET_TESTFRAME">APPLET_TESTFRAME</a>,
 *   <a href="../../../overview-summary.html#PUBLIC">PUBLIC</a>,
 *   <a href="../../../overview-summary.html#ASSERT">ASSERT</a>
 */
 class Exponent_perf_description {

    //#########################################################################
    // Variable declarations
    // 


        /**
         * Card variable declararion from Exponent_perf.id.
         * <P>
         * Only available if either JAVACARD_APPLET
         * or APPLET_TESTFRAME is defined.
         */
        /* package local */ Exponent_perf_card exponent_perf_card;



    /**
     * Variable declaration from Exponent_perf.id.
     */
    /* package local */ Test_protocols test_protocols;
    /**
     * Variable declaration from Exponent_perf.id.
     */
    /* package local */ Bignats bignats;
    /**
     * Variable declaration from Exponent_perf.id.
     */
    /* package local */ Bignat one_or_correction;
    /**
     * Variable declaration from Exponent_perf.id.
     */
    /* package local */ Modulus vec_exp_modulus;
    /**
     * Variable declaration from Exponent_perf.id.
     */
    /* package local */ APDU_short n1;
    /**
     * Variable declaration from Exponent_perf.id.
     */
    /* package local */ APDU_short n2;
    /**
     * Variable declaration from Exponent_perf.id.
     */
    /* package local */ APDU_short vector_exp_variant;
    /**
     * Variable declaration from Exponent_perf.id.
     */
    /* package local */ APDU_boolean keep_modulus;
    /**
     * Variable declaration from Exponent_perf.id.
     */
    /* package local */ Bignat result;


    //#########################################################################
    //#########################################################################
    // 
    // Protocol Vector_length
    // 
    //#########################################################################
    //#########################################################################

    //#########################################################################
    // Step methods
    // 



      /**
       * Card action for step set_vector_length in protocol Vector_length.
       * <P>
       * Only available if JAVACARD_APPLET or APPLET_TESTFRAME is defined.
       */
      /* package local */ class set_vector_length_call implements Void_method {
          /** Empty constructor. */
          /* package */ set_vector_length_call() {}

          /**
           * Run the card action for step set_vector_length in protocol Vector_length.
           */
          public void method() {
              Resize.resize_vectors(n1.value, n2.value);
         test_protocols.set_result_sizes();
              return;
          }
      }




    //#########################################################################
    // Steps
    // 

    /**
     * Step instance for step set_vector_length in protocol Vector_length.
     */
    Protocol_step set_vector_length_step;



    /**
     * Initialize {@link #set_vector_length_step}.
     * Initialize the step instance for step set_vector_length in protocol Vector_length.
     */
    private void init_set_vector_length_step() {
        if(set_vector_length_step != null)
            return;

        APDU_Serializable[] args = new APDU_Serializable[]{
            n1,
            n2
        };

        APDU_Serializable[] res = null;

        set_vector_length_step =
            new Protocol_step(
                (byte)0, // P1
                args, // args

                    new set_vector_length_call(), // method

                res // results
            );
        return;
    }


    /**
     * Update step instance in {@link #set_vector_length_step}.
     * Update argument and result references in the step set_vector_length
     * of protocol Vector_length.
     */
    public void update_set_vector_length_step() {
        Misc.myassert(set_vector_length_step != null, (short)(0));

        set_vector_length_step.arguments[0] = n1;
        set_vector_length_step.arguments[1] = n2;
        return;
    }



    //#########################################################################
    // Vector_length protocol definition
    // 

    /**
     * Protocol instance for protocol Vector_length.
     */
    public Protocol vector_length_protocol;

    /**
     * Initialize {@link #vector_length_protocol}.
     * Initialize the protocol instance for protocol Vector_length.
     */
    private void init_vector_length_protocol() {
        if(vector_length_protocol != null)
            return;

        init_set_vector_length_step();

        Protocol_step[] steps = new Protocol_step[]{
            set_vector_length_step
        };
        vector_length_protocol = new Protocol(steps);
        return;
    }


    /**
     * Update {@link #vector_length_protocol}.
     * Update argument and result references in all 
     * steps of protocol Vector_length.
     */
    public void update_vector_length_protocol() {
        update_set_vector_length_step();
        vector_length_protocol.set_result_sizes();
    }


    //#########################################################################
    //#########################################################################
    // 
    // Protocol Vector_exp
    // 
    //#########################################################################
    //#########################################################################

    //#########################################################################
    // Step methods
    // 



      /**
       * Card action for step vector_exp_choose_mod in protocol Vector_exp.
       * <P>
       * Only available if JAVACARD_APPLET or APPLET_TESTFRAME is defined.
       */
      /* package local */ class vector_exp_choose_mod_call implements Void_method {
          /** Empty constructor. */
          /* package */ vector_exp_choose_mod_call() {}

          /**
           * Run the card action for step vector_exp_choose_mod in protocol Vector_exp.
           */
          public void method() {
              if(vector_exp_variant.value == (short)2) {

                vec_exp_modulus = bignats.mult_modulus;



         } else {
             vec_exp_modulus = bignats.modulus;
         }
         Misc.myassert(bignats.mult_modulus.size() == bignats.modulus.size(), (short)(0));
         update_vector_exp_init_step();
              return;
          }
      }

      /**
       * Card action for step vector_exp_init in protocol Vector_exp.
       * <P>
       * Only available if JAVACARD_APPLET or APPLET_TESTFRAME is defined.
       */
      /* package local */ class vector_exp_init_call implements Void_method {
          /** Empty constructor. */
          /* package */ vector_exp_init_call() {}

          /**
           * Run the card action for step vector_exp_init in protocol Vector_exp.
           */
          public void method() {
              exponent_perf_card.vector_exp_init(vec_exp_modulus,
                                            vector_exp_variant.value,
                                            keep_modulus.value);
              return;
          }
      }

      /**
       * Card action for step vector_exp_1 in protocol Vector_exp.
       * <P>
       * Only available if JAVACARD_APPLET or APPLET_TESTFRAME is defined.
       */
      /* package local */ class vector_exp_1_call implements Void_method {
          /** Empty constructor. */
          /* package */ vector_exp_1_call() {}

          /**
           * Run the card action for step vector_exp_1 in protocol Vector_exp.
           */
          public void method() {
              exponent_perf_card.vector_exp(bignats.base, bignats.exponent,
                                       vec_exp_modulus,
                                       n1.value, bignats.base_factors,
                                       one_or_correction,
                                       vector_exp_variant.value,
                                       false);
              return;
          }
      }

      /**
       * Card action for step vector_exp_2 in protocol Vector_exp.
       * <P>
       * Only available if JAVACARD_APPLET or APPLET_TESTFRAME is defined.
       */
      /* package local */ class vector_exp_2_call implements Void_method {
          /** Empty constructor. */
          /* package */ vector_exp_2_call() {}

          /**
           * Run the card action for step vector_exp_2 in protocol Vector_exp.
           */
          public void method() {
              exponent_perf_card.vector_exp(bignats.base, bignats.exponent,
                                       vec_exp_modulus,
                                       n1.value, bignats.base_factors,
                                       one_or_correction,
                                       vector_exp_variant.value,
                                       true);
              return;
          }
      }




    //#########################################################################
    // Steps
    // 

    /**
     * Step instance for step vector_exp_choose_mod in protocol Vector_exp.
     */
    Protocol_step vector_exp_choose_mod_step;

    /**
     * Step instance for step vector_exp_init in protocol Vector_exp.
     */
    Protocol_step vector_exp_init_step;

    /**
     * Step instance for step vector_exp_1 in protocol Vector_exp.
     */
    Protocol_step vector_exp_1_step;

    /**
     * Step instance for step vector_exp_2 in protocol Vector_exp.
     */
    Protocol_step vector_exp_2_step;

    /**
     * Step instance for step vector_exp_result in protocol Vector_exp.
     */
    Protocol_step vector_exp_result_step;



    /**
     * Initialize {@link #vector_exp_choose_mod_step}.
     * Initialize the step instance for step vector_exp_choose_mod in protocol Vector_exp.
     */
    private void init_vector_exp_choose_mod_step() {
        if(vector_exp_choose_mod_step != null)
            return;

        APDU_Serializable[] args = new APDU_Serializable[]{
            vector_exp_variant
        };

        APDU_Serializable[] res = null;

        vector_exp_choose_mod_step =
            new Protocol_step(
                (byte)0, // P1
                args, // args

                    new vector_exp_choose_mod_call(), // method

                res // results
            );
        return;
    }


    /**
     * Update step instance in {@link #vector_exp_choose_mod_step}.
     * Update argument and result references in the step vector_exp_choose_mod
     * of protocol Vector_exp.
     */
    public void update_vector_exp_choose_mod_step() {
        Misc.myassert(vector_exp_choose_mod_step != null, (short)(0));

        vector_exp_choose_mod_step.arguments[0] = vector_exp_variant;
        return;
    }


    /**
     * Initialize {@link #vector_exp_init_step}.
     * Initialize the step instance for step vector_exp_init in protocol Vector_exp.
     */
    private void init_vector_exp_init_step() {
        if(vector_exp_init_step != null)
            return;

        APDU_Serializable[] args = new APDU_Serializable[]{
            bignats.base,
            bignats.exponent,
            vec_exp_modulus,
            n1,
            bignats.base_factors,
            one_or_correction,
            keep_modulus
        };

        APDU_Serializable[] res = null;

        vector_exp_init_step =
            new Protocol_step(
                (byte)1, // P1
                args, // args

                    new vector_exp_init_call(), // method

                res // results
            );
        return;
    }


    /**
     * Update step instance in {@link #vector_exp_init_step}.
     * Update argument and result references in the step vector_exp_init
     * of protocol Vector_exp.
     */
    public void update_vector_exp_init_step() {
        Misc.myassert(vector_exp_init_step != null, (short)(0));

        vector_exp_init_step.arguments[0] = bignats.base;
        vector_exp_init_step.arguments[1] = bignats.exponent;
        vector_exp_init_step.arguments[2] = vec_exp_modulus;
        vector_exp_init_step.arguments[3] = n1;
        vector_exp_init_step.arguments[4] = bignats.base_factors;
        vector_exp_init_step.arguments[5] = one_or_correction;
        vector_exp_init_step.arguments[6] = keep_modulus;
        return;
    }


    /**
     * Initialize {@link #vector_exp_1_step}.
     * Initialize the step instance for step vector_exp_1 in protocol Vector_exp.
     */
    private void init_vector_exp_1_step() {
        if(vector_exp_1_step != null)
            return;

        APDU_Serializable[] args = null;

        APDU_Serializable[] res = null;

        vector_exp_1_step =
            new Protocol_step(
                (byte)2, // P1
                args, // args

                    new vector_exp_1_call(), // method

                res // results
            );
        return;
    }


    /**
     * Update step instance in {@link #vector_exp_1_step}.
     * Update argument and result references in the step vector_exp_1
     * of protocol Vector_exp.
     */
    public void update_vector_exp_1_step() {
        Misc.myassert(vector_exp_1_step != null, (short)(0));

        return;
    }


    /**
     * Initialize {@link #vector_exp_2_step}.
     * Initialize the step instance for step vector_exp_2 in protocol Vector_exp.
     */
    private void init_vector_exp_2_step() {
        if(vector_exp_2_step != null)
            return;

        APDU_Serializable[] args = null;

        APDU_Serializable[] res = null;

        vector_exp_2_step =
            new Protocol_step(
                (byte)3, // P1
                args, // args

                    new vector_exp_2_call(), // method

                res // results
            );
        return;
    }


    /**
     * Update step instance in {@link #vector_exp_2_step}.
     * Update argument and result references in the step vector_exp_2
     * of protocol Vector_exp.
     */
    public void update_vector_exp_2_step() {
        Misc.myassert(vector_exp_2_step != null, (short)(0));

        return;
    }


    /**
     * Initialize {@link #vector_exp_result_step}.
     * Initialize the step instance for step vector_exp_result in protocol Vector_exp.
     */
    private void init_vector_exp_result_step() {
        if(vector_exp_result_step != null)
            return;

        APDU_Serializable[] args = null;

        APDU_Serializable[] res = new APDU_Serializable[]{
            result
        };

        vector_exp_result_step =
            new Protocol_step(
                (byte)4, // P1
                args, // args

                    new Empty_void_method(), // method

                res // results
            );
        return;
    }


    /**
     * Update step instance in {@link #vector_exp_result_step}.
     * Update argument and result references in the step vector_exp_result
     * of protocol Vector_exp.
     */
    public void update_vector_exp_result_step() {
        Misc.myassert(vector_exp_result_step != null, (short)(0));

        vector_exp_result_step.results[0] = result;
        return;
    }



    //#########################################################################
    // Vector_exp protocol definition
    // 

    /**
     * Protocol instance for protocol Vector_exp.
     */
    public Protocol vector_exp_protocol;

    /**
     * Initialize {@link #vector_exp_protocol}.
     * Initialize the protocol instance for protocol Vector_exp.
     */
    private void init_vector_exp_protocol() {
        if(vector_exp_protocol != null)
            return;

        init_vector_exp_choose_mod_step();
        init_vector_exp_init_step();
        init_vector_exp_1_step();
        init_vector_exp_2_step();
        init_vector_exp_result_step();

        Protocol_step[] steps = new Protocol_step[]{
            vector_exp_choose_mod_step,
            vector_exp_init_step,
            vector_exp_1_step,
            vector_exp_2_step,
            vector_exp_result_step
        };
        vector_exp_protocol = new Protocol(steps);
        return;
    }


    /**
     * Update {@link #vector_exp_protocol}.
     * Update argument and result references in all 
     * steps of protocol Vector_exp.
     */
    public void update_vector_exp_protocol() {
        update_vector_exp_choose_mod_step();
        update_vector_exp_init_step();
        update_vector_exp_1_step();
        update_vector_exp_2_step();
        update_vector_exp_result_step();
        vector_exp_protocol.set_result_sizes();
    }


    /**
     * Update all protocols in this object.
     * Update all argument and result references in all
     * steps of all protocol instances described in Exponent_perf.id.
     */
    public void update_all() {
        update_vector_length_protocol();
        update_vector_exp_protocol();
    }


    //#########################################################################
    //#########################################################################
    // 
    // constructor: initialize protocols
    // 
    //#########################################################################
    //#########################################################################

    /**
     * Construct protocol descriptions.
     * Construct and initialize the protocol descriptions
     * for all protocols described in Exponent_perf.id,
     * except for those that are declared as delayed there.
     */
    public Exponent_perf_description(Test_protocols test_protocols, Bignats bignats) {
        // initialize variables
        n1 = new APDU_short();
        n2 = new APDU_short();
        vector_exp_variant = new APDU_short();
        keep_modulus = new APDU_boolean();

            exponent_perf_card = new Exponent_perf_card(bignats);


        // constructor statements
        this.test_protocols = test_protocols;
        this.bignats = bignats;
        one_or_correction = bignats.n_1;
        vec_exp_modulus = bignats.modulus;
        result = bignats.r_1;

        // initialize protocols
        init_vector_length_protocol();
        init_vector_exp_protocol();
        return;
    }
}
