// 
// OV-chip 2.0 project
// 
// Digital Security (DS) group at Radboud Universiteit Nijmegen
// 
// Copyright (C) 2009
// 
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License as
// published by the Free Software Foundation; either version 2 of
// the License, or (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
// General Public License in file COPYING in this or one of the
// parent directories for more details.
// 
// Created 19.12.08 by Hendrik
// 
// netbeans generated code for the base selection dialog
// 
// $Id: Base_selection.java,v 1.5 2009-05-14 17:57:29 tews Exp $

package ds.ov2.gui;

/**
 * netbeans generated code for the base selection dialog. This class
 * contains only the code to create the window with all its
 * components. The actions that are performed are in {@link
 * Bases_actions}.
 *
 *
 * @author Hendrik Tews
 * @version $Revision: 1.5 $
 * @commitdate $Date: 2009-05-14 17:57:29 $ by $Author: tews $
 * @environment host
 * @CPP no cpp preprocessing needed
 */
public class Base_selection extends javax.swing.JDialog {

    /** serialVersionUID for the Serializable interface */
    public static final long serialVersionUID = 1L;

    /**
     * 
     * The actions instance.
     */
    public final Bases_actions bases_actions;

    /** Initially false. Changed to true when the dialog is left via OK. */
    public boolean finished_ok = false;
    

    /** Creates new form Base_selection */
    public Base_selection(java.awt.Frame parent, boolean modal, Bases_actions bases_actions) {
        super(parent, modal);
        this.bases_actions = bases_actions;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        base_0_panel = new javax.swing.JPanel();
        base_0_label = new javax.swing.JLabel();
        base_0_spinner = new javax.swing.JSpinner();
        base_1_panel = new javax.swing.JPanel();
        base_1_label = new javax.swing.JLabel();
        base_1_spinner = new javax.swing.JSpinner();
        base_2_panel = new javax.swing.JPanel();
        base_2_label = new javax.swing.JLabel();
        base_2_spinner = new javax.swing.JSpinner();
        base_3_panel = new javax.swing.JPanel();
        base_3_label = new javax.swing.JLabel();
        base_3_spinner = new javax.swing.JSpinner();
        base_4_panel = new javax.swing.JPanel();
        base_4_label = new javax.swing.JLabel();
        base_4_spinner = new javax.swing.JSpinner();
        ok_button = new javax.swing.JButton();
        dismiss_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Select Bases"));

        base_0_label.setText("base 0");

        javax.swing.GroupLayout base_0_panelLayout = new javax.swing.GroupLayout(base_0_panel);
        base_0_panel.setLayout(base_0_panelLayout);
        base_0_panelLayout.setHorizontalGroup(
            base_0_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(base_0_panelLayout.createSequentialGroup()
                .addComponent(base_0_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(base_0_spinner, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE))
        );
        base_0_panelLayout.setVerticalGroup(
            base_0_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(base_0_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(base_0_label)
                .addComponent(base_0_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        base_1_label.setText("base 1");

        javax.swing.GroupLayout base_1_panelLayout = new javax.swing.GroupLayout(base_1_panel);
        base_1_panel.setLayout(base_1_panelLayout);
        base_1_panelLayout.setHorizontalGroup(
            base_1_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(base_1_panelLayout.createSequentialGroup()
                .addComponent(base_1_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(base_1_spinner, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE))
        );
        base_1_panelLayout.setVerticalGroup(
            base_1_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(base_1_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(base_1_label)
                .addComponent(base_1_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        base_2_label.setText("base 2");

        javax.swing.GroupLayout base_2_panelLayout = new javax.swing.GroupLayout(base_2_panel);
        base_2_panel.setLayout(base_2_panelLayout);
        base_2_panelLayout.setHorizontalGroup(
            base_2_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(base_2_panelLayout.createSequentialGroup()
                .addComponent(base_2_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(base_2_spinner, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE))
        );
        base_2_panelLayout.setVerticalGroup(
            base_2_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(base_2_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(base_2_label)
                .addComponent(base_2_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        base_3_label.setText("base 3");

        javax.swing.GroupLayout base_3_panelLayout = new javax.swing.GroupLayout(base_3_panel);
        base_3_panel.setLayout(base_3_panelLayout);
        base_3_panelLayout.setHorizontalGroup(
            base_3_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(base_3_panelLayout.createSequentialGroup()
                .addComponent(base_3_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(base_3_spinner, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE))
        );
        base_3_panelLayout.setVerticalGroup(
            base_3_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(base_3_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(base_3_label)
                .addComponent(base_3_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        base_4_label.setText("base 4");

        javax.swing.GroupLayout base_4_panelLayout = new javax.swing.GroupLayout(base_4_panel);
        base_4_panel.setLayout(base_4_panelLayout);
        base_4_panelLayout.setHorizontalGroup(
            base_4_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(base_4_panelLayout.createSequentialGroup()
                .addComponent(base_4_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(base_4_spinner, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE))
        );
        base_4_panelLayout.setVerticalGroup(
            base_4_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(base_4_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(base_4_label)
                .addComponent(base_4_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ok_button.setText("OK");
        ok_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_buttonActionPerformed(evt);
            }
        });

        dismiss_button.setText("Dismiss");
        dismiss_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dismiss_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(base_0_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(base_1_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(base_2_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(base_3_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(base_4_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ok_button, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(dismiss_button, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                        .addGap(182, 182, 182))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(base_0_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(base_1_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(base_2_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(base_3_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(base_4_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ok_button)
                    .addComponent(dismiss_button))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dismiss_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dismiss_buttonActionPerformed
        bases_actions.dismiss_button(this);
}//GEN-LAST:event_dismiss_buttonActionPerformed

    private void ok_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_buttonActionPerformed
        bases_actions.ok_button(this);
    }//GEN-LAST:event_ok_buttonActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JLabel base_0_label;
    private javax.swing.JPanel base_0_panel;
    javax.swing.JSpinner base_0_spinner;
    javax.swing.JLabel base_1_label;
    private javax.swing.JPanel base_1_panel;
    javax.swing.JSpinner base_1_spinner;
    javax.swing.JLabel base_2_label;
    private javax.swing.JPanel base_2_panel;
    javax.swing.JSpinner base_2_spinner;
    javax.swing.JLabel base_3_label;
    private javax.swing.JPanel base_3_panel;
    javax.swing.JSpinner base_3_spinner;
    javax.swing.JLabel base_4_label;
    private javax.swing.JPanel base_4_panel;
    javax.swing.JSpinner base_4_spinner;
    private javax.swing.JButton dismiss_button;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton ok_button;
    // End of variables declaration//GEN-END:variables

}
